version: '3.8'

services:
  php:
     build: ./php
     image: php82
     volumes:
       - ./html:/var/www/html
     depends_on:
       - mysql
     restart: always
     ports:
      - 3100:80

  mysql:
    ports:
      - 3101:3306
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: job_search_wp
      MYSQL_ROOT_PASSWORD: En2aqskS
      MYSQL_PASSWORD: root
    restart: always
    volumes:
      - job_search_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=En2aqskS
    ports:
      - 3002:80
    links:
      - mysql
    volumes:
      - ./phpmyadmin/sessions:/sessions
  
volumes:
  job_search_data:


#wp_pass:L5B$lHTfAtH!